/*
 * This source file was generated by the Gradle 'init' task
 */
package core;

import custom_item.AbstractItem;
import custom_item.GiveItemCommand;
import custom_item.Listener;
import plugin_items.FireSword;
import org.bukkit.Bukkit;
import org.bukkit.plugin.java.JavaPlugin;

public class ExamplePlugin extends JavaPlugin {


  @Override
  public void onEnable() {

    System.out.println("Плагин был загружен!");
    
    registerCommand("giveitem", new GiveItemCommand());
    AbstractItem.registerItem(new FireSword());
    Bukkit.getPluginManager().registerEvents(new Listener(), this);

  }

  @Override
  public void onDisable() {
    System.out.println("Плагин был выключен!");
  }
  
}